### ISSUE TITLE
Blue Sirius fails to appear

### ISSUE THREAD

**Issue by LavenderTheGreat** [LavenderTheGreat/Yu-Gi-Oh-Card-Viewer#1]
Card Name | Issue in detail | Expected
------------ | ------------- | -------------
Blue Sirius | Lacks all metadata | Has metadata

**Comment by LavenderTheGreatGB** [comment]
http://yugioh.wikia.com/wiki/Celestial_Wolf_Lord,_Blue_Sirius pretty sure the issue is here, the list used a shortened name.

**Comment by LavenderTheGreatGB** [comment]
Correction, it occurred because when I parsed the list it split the name at the comma, making two cards, Celestial Wolf Lord and Blue Sirius.

**Comment by LavenderTheGreat** [comment]
Fixed in the cardlist json.
